### ISSUE TITLE
Replace Bootstrap with Zurd Foundation

### ISSUE THREAD

**Issue by d3orn** [d3orn/hikomsys#8]
stop using Bootstrap and get started with Foundation in all views

**Comment by mircealungu** [comment]
why the change? :)

2014-03-24 11:58 GMT+01:00 d3orn notifications@github.com:

**Comment by d3orn** [comment]
almost done. You should check it out.

**Comment by mircealungu** [comment]
Awesome :)

Two small observations:
- i tried to provide this as the git url and failed:
  git@github.com:mircealungu/Pomodoro-Box.git
  . clarify that you are interested in the github url of the project.
- i see a strange duplication bug in the tree (see screenshot)

Cheers,
m.

)[image: Imagini inline 1]

2014-03-25 16:12 GMT+01:00 d3orn notifications@github.com:

**Comment by d3orn** [comment]
thanks for reporting a bug 
I cannot look at your pictures but I found out what you mean - working on it
(the problem is that my system thinks pomodoro-box.git is not the same as pomodoro-box, without the .git) that is why I still add the stuff to the table which ofc has the same name => each entry gets duplicated

**Comment by d3orn** [comment]
This is done and it looks amazing!

**Comment by mircealungu** [comment]
Nice :)
I would like to see it, but my VPN connection does not work at the moment.
I'll have to wait until I'll be at the uni. But probably, by then, it will
be even more amazing :)

A nice evening,
M.

2014-04-12 20:59 GMT+02:00 d3orn notifications@github.com:
